{application,freyr,
             [{description,[]},
              {vsn,"1"},
              {modules,[freyr_app,freyr_listener,freyr_parser,freyr_storage,
                        freyr_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,lager]},
              {mod,{freyr_app,[]}},
              {env,[]}]}.
