{application,freyr,
             [{description,[]},
              {vsn,"1"},
              {modules,[freyr_app,freyr_builder,freyr_listener,freyr_logger,
                        freyr_storage,freyr_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,lager]},
              {mod,{freyr_app,[]}},
              {env,[]}]}.
